import Foundation
import UIKit

// MARK: - Configuration

/// Top-level SDK configuration. Pass to ``VerisCapture/initialise(config:completion:)``.
public struct VerisConfig {
    /// Your Veris production or sandbox license key.
    public let licenseKey: String
    /// Unique nonce for this SDK initialisation — generated by your backend.
    public let initNonce: String
    /// Whether to play voice instructions.
    public var voiceEnabled: Bool
    /// Whether to trigger haptic feedback during capture.
    public var hapticEnabled: Bool
    /// Feature set to use if the remote flag fetch fails.
    public var fallbackFeatures: VerisFeatureFlags
    /// Target environment.
    public var environment: VerisEnvironment
    /// Base URL for Veris API.
    public var apiBaseUrl: String

    public init(
        licenseKey: String,
        initNonce: String,
        voiceEnabled: Bool = true,
        hapticEnabled: Bool = true,
        fallbackFeatures: VerisFeatureFlags = .starter,
        environment: VerisEnvironment = .production,
        apiBaseUrl: String = "https://api.verisinfra.com"
    ) {
        self.licenseKey = licenseKey
        self.initNonce = initNonce
        self.voiceEnabled = voiceEnabled
        self.hapticEnabled = hapticEnabled
        self.fallbackFeatures = fallbackFeatures
        self.environment = environment
        self.apiBaseUrl = apiBaseUrl
    }
}

public enum VerisEnvironment { case production, sandbox }

// MARK: - Session Configuration

/// Configuration for a single verification session.
public struct VerisSessionConfig {
    /// Unique nonce generated by YOUR backend per session. Embedded in the signed result to prevent replay.
    public let nonce: String
    /// Opaque user identifier — never sent to Veris servers.
    public let userId: String?
    /// Liveness strictness override for this session.
    public var strictness: VerisStrictness
    /// Max capture retries before delivering a failure result.
    public var maxRetries: Int
    /// Max session duration in seconds.
    public var sessionTimeoutSecs: Int
    /// Minimum acceptable quality score.
    public var minQualityScore: Float
    /// Minimum stable frames before capture.
    public var minStabilityFrames: Int
    /// Pro/Enterprise only: number of liveness challenge rounds (2–4). Clamped by the SDK.
    public var proRandomChallengeCount: Int
    /// Pro/Enterprise only: force active liveness even when passive evidence already passed.
    public var enforceChallenge: Bool

    public init(
        nonce: String,
        userId: String? = nil,
        strictness: VerisStrictness = .medium,
        maxRetries: Int = 3,
        sessionTimeoutSecs: Int = 60,
        minQualityScore: Float = 0.70,
        minStabilityFrames: Int = 5,
        proRandomChallengeCount: Int = 2,
        enforceChallenge: Bool = false
    ) {
        self.nonce = nonce
        self.userId = userId
        self.strictness = strictness
        self.maxRetries = maxRetries
        self.sessionTimeoutSecs = sessionTimeoutSecs
        self.minQualityScore = minQualityScore
        self.minStabilityFrames = minStabilityFrames
        self.proRandomChallengeCount = proRandomChallengeCount
        self.enforceChallenge = enforceChallenge
    }
}

public enum VerisStrictness { case low, medium, high }

// MARK: - Feature Flags

/// Remotely-delivered feature flags for the authenticated client plan.
///
/// Field set mirrors the Android `VerisFeatureFlags` data class so every
/// cross-platform bridge (Flutter, React Native) serialises an identical
/// payload regardless of host OS.
public struct VerisFeatureFlags {
    // ── Capture ──────────────────────────────────────────────────────────────
    public var faceCapture: Bool
    public var qualityChecks: Bool
    public var voiceInstructions: Bool
    public var humanValidation: Bool
    public var facialLandmarkAnalysis: Bool
    public var passiveLiveness: Bool
    public var activeLiveness: Bool
    public var activeLivenessChallenges: Int
    public var activeLivenessConfigurable: Bool
    public var videoCapture: Bool
    public var advancedConfig: Bool
    /// True when Veris-only branding is enforced on the capture UI (server `capture_branding == "required"`).
    public var captureBranding: Bool
    /// nil = unlimited.
    public var captureMonthlyLimit: Int?
    // ── Scan ─────────────────────────────────────────────────────────────────
    public var scanEnabled: Bool
    /// nil = unlimited.
    public var scanMonthlyLimit: Int?
    // ── Compare ──────────────────────────────────────────────────────────────
    public var compare: Bool
    public var compareQuotaRemaining: Int
    public var compareQuotaMonthly: Int

    /// Default features for Starter/Spark plan (safe fallback if network is unavailable).
    public static let starter = VerisFeatureFlags(
        faceCapture: true, qualityChecks: true, voiceInstructions: true,
        humanValidation: false, facialLandmarkAnalysis: false,
        passiveLiveness: false, activeLiveness: false, activeLivenessChallenges: 0,
        activeLivenessConfigurable: false, videoCapture: false, advancedConfig: false,
        captureBranding: true, captureMonthlyLimit: nil,
        scanEnabled: false, scanMonthlyLimit: nil,
        compare: false, compareQuotaRemaining: 0, compareQuotaMonthly: 0
    )

    public init(
        faceCapture: Bool = true,
        qualityChecks: Bool = true,
        voiceInstructions: Bool = true,
        humanValidation: Bool = false,
        facialLandmarkAnalysis: Bool = false,
        passiveLiveness: Bool = false,
        activeLiveness: Bool = false,
        activeLivenessChallenges: Int = 0,
        activeLivenessConfigurable: Bool = false,
        videoCapture: Bool = false,
        advancedConfig: Bool = false,
        captureBranding: Bool = true,
        captureMonthlyLimit: Int? = nil,
        scanEnabled: Bool = false,
        scanMonthlyLimit: Int? = nil,
        compare: Bool = false,
        compareQuotaRemaining: Int = 0,
        compareQuotaMonthly: Int = 0
    ) {
        self.faceCapture = faceCapture
        self.qualityChecks = qualityChecks
        self.voiceInstructions = voiceInstructions
        self.humanValidation = humanValidation
        self.facialLandmarkAnalysis = facialLandmarkAnalysis
        self.passiveLiveness = passiveLiveness
        self.activeLiveness = activeLiveness
        self.activeLivenessChallenges = activeLivenessChallenges
        self.activeLivenessConfigurable = activeLivenessConfigurable
        self.videoCapture = videoCapture
        self.advancedConfig = advancedConfig
        self.captureBranding = captureBranding
        self.captureMonthlyLimit = captureMonthlyLimit
        self.scanEnabled = scanEnabled
        self.scanMonthlyLimit = scanMonthlyLimit
        self.compare = compare
        self.compareQuotaRemaining = compareQuotaRemaining
        self.compareQuotaMonthly = compareQuotaMonthly
    }
}

// MARK: - Subscription State

public enum VerisSubscriptionState {
    case unknown
    case active(VerisLicenseInfo)
    case gracePeriod(VerisLicenseInfo)
    case expired
}

public struct VerisLicenseInfo {
    public let clientId: String
    public let plan: String
    public let features: VerisFeatureFlags
    public let expiresAt: Date
    public let graceExpiresAt: Date
    public let inGracePeriod: Bool
    public let gracePeriodHours: Int
    public var environment: String = "production"
    public var licenseKeyId: String = ""
}

// MARK: - Init Results

public enum VerisInitResult {
    case ready(VerisLicenseInfo)
    case gracePeriod(VerisLicenseInfo)
    case subscriptionExpired
    case initError(String)
}

// MARK: - Verification Results

/// The final result of a verification session.
/// Delivered exactly once via the completion block. The SDK never blocks on failure.
public enum VerisResult {
    /// Verification passed.
    /// - signedResult: JWT signed by Veris — verify on your backend with the Veris public key.
    /// - faceImage: UIImage of the captured face — stays in the host app, never sent to Veris.
    case success(VerisSuccessPayload)
    /// Verification failed. `retryable` indicates whether the user can try again.
    case failure(VerisError, String, retryable: Bool)
    /// User dismissed the verification UI before completing.
    case cancelled
    /// Subscription is inactive. Host app must handle.
    case subscriptionInactive(String)
    /// Unexpected SDK error. Always retryable.
    case error(VerisError, String)
}

public struct VerisSuccessPayload {
    /// JWT signed by Veris — verify this on your backend.
    public let signedResult: String
    /// Captured face image — stays in the host app, not sent to Veris.
    public let faceImage: UIImage
    public let qualityScore: Float
    public let livenessScore: Float?
    public let confidenceScore: Float?
    /// Non-nil only if Pro plan with videoCapture enabled.
    public let videoData: Data?
}

// MARK: - Error Codes

public enum VerisError: Int {
    // Capture
    case noFaceDetected         = 1001
    case multipleFacesDetected  = 1002
    case faceTooClose           = 1003
    case faceTooFar             = 1004
    case poorLighting           = 1005
    case excessiveMotion        = 1006
    case occlusionDetected      = 1007
    case poorImageQuality       = 1008

    // Liveness
    case livenessFailed         = 2001
    case livenessTimeout        = 2002
    case challengeNotCompleted  = 2003

    // Spoofing
    case spoofingDetected       = 3001
    case staticFrameDetected    = 3002

    // Session
    case maxRetriesExceeded     = 4001
    case sessionTimeout         = 4002
    case nonceInvalid           = 4003

    // System
    case cameraPermissionDenied = 5001
    case cameraNotAvailable     = 5002
    case sdkNotInitialised      = 5003
    case networkError           = 5004
    case subscriptionExpired    = 5005
}

public enum VerisErrorMessages {
    public static func message(for error: VerisError) -> String {
        switch error {
        case .noFaceDetected:          return "We couldn't detect a face. Please look directly at the camera."
        case .multipleFacesDetected:   return "We can see more than one person. Please make sure you're alone in frame."
        case .faceTooClose:            return "You're a little too close. Move back slightly."
        case .faceTooFar:              return "Move a little closer to the camera."
        case .poorLighting:            return "The lighting is too low. Try facing a window or a light source."
        case .excessiveMotion:         return "Hold still while we capture."
        case .occlusionDetected:       return "Something is covering part of your face."
        case .poorImageQuality:        return "The image quality is too low. Try again in better conditions."
        case .livenessFailed:          return "We couldn't confirm a live person. Please try again in good lighting."
        case .livenessTimeout:         return "The liveness check timed out. Please try again."
        case .challengeNotCompleted:   return "Please follow the on-screen instructions."
        case .spoofingDetected:        return "Verification failed. Please use a live camera — not a photo."
        case .staticFrameDetected:     return "The image didn't change. Ensure you're using a live camera."
        case .maxRetriesExceeded:      return "Too many attempts. Please try again later."
        case .sessionTimeout:          return "The session timed out. Please start again."
        case .nonceInvalid:            return "Session token is invalid. Please start a new verification."
        case .cameraPermissionDenied:  return "Camera access is required. Please grant permission in Settings."
        case .cameraNotAvailable:      return "The camera is not available right now."
        case .sdkNotInitialised:       return "SDK has not been initialised. Call VerisCapture.shared.initialise() first."
        case .networkError:            return "A network error occurred. Please check your connection."
        case .subscriptionExpired:     return "Your Veris subscription has expired."
        }
    }
}
